[theme]
base = "dark"
primaryColor = "#3fcfc4"
backgroundColor = "#050e07"
secondaryBackgroundColor = "#0e2015"
textColor = "#dff0e2"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
